# Generated by Django 4.2 on 2023-04-19 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0010_add_is_seen_field_to_service_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_of_event',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
