# Generated by Django 4.2 on 2023-04-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_add_invited_user_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('text', models.TextField()),
            ],
        ),
    ]
