# Generated by Django 4.2 on 2023-05-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_add_contact_form_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='in_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
